HairSalon/Models/Client.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace HairSalon.Models
{
    public class Client
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public int StylistId { get; set; }

        public virtual Stylist Stylist { get; set; }

    }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;
using HairSalon.Models;

namespace HairSalon.Models
{
    public class HairSalonContext : DbContext
    {
        public virtual DbSet<Stylist> Stylists { get; set; }
        public DbSet<Client> Clients { get; set; }

        public HairSalonContext(DbContextOptions options) : base(options) { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLazyLoadingProxies();
        }
    }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
    public class Stylist
    {
        public Stylist()
        {
            this.Clients = new HashSet<Client>();
        }

        public int StylistId { get; set; }
        public string StylistName { get; set; }
        public string StylistDetails { get; set; }
        public virtual ICollection<Client> Clients { get; set; }

    }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class ClientsController : Controller
    {
        private readonly HairSalonContext _db;
        public ClientsController(HairSalonContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Client client)
        {
            _db.Clients.Add(client);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            return View(thisClient);
        }

        public ActionResult Edit(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
            return View(thisClient);
        }

        [HttpPost]
        public ActionResult Edit(Client client)
        {
            _db.Entry(client).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            return View(thisClient);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            _db.Clients.Remove(thisClient);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class StylistsController : Controller
    {
        private readonly HairSalonContext _db;

        public StylistsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Stylist> model = _db.Stylists.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Stylist stylist)
        {
            _db.Stylists.Add(stylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
            return View(thisStylist);
        }

        public ActionResult Edit(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
            return View(thisStylist);
        }

        [HttpPost]
        public ActionResult Edit(Stylist stylist)
        {
            _db.Entry(stylist).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
            return View(thisStylist);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
            _db.Stylists.Remove(thisStylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Views/Clients/Create.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add a new client</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.ClientName)
    @Html.TextBoxFor(model => model.ClientName)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Add new client" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this client?</h2>

@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Clients/Details.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)<h3>

        <p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
        <p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Edit</h2>

<h4>Edit this client: @Html.DisplayFor(model => model.ClientName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientId)

    @Html.LabelFor(model => model.ClientName)
    @Html.EditorFor(model => model.ClientName)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
    Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
    <h3>No clients have been added yet</h3>
}

<ul>
    @foreach (Client client in Model)
    {
        <li>@Html.ActionLink($"{client.ClientName}", "Details", new { id = client.ClientId }) | @client.Stylist.StylistName
        </li>
    }
</ul>

<p>@Html.ActionLink("Add new client", "Create")</p>

HairSalon/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
<html>

<body>
    <h1>Welcome Claire!</h1>
    <h2>This application will help you manage your stylists and their clients</h2>
    <h2>@Html.ActionLink("See all stylists", "Index", "Stylists")</h2>
    <h3>@Html.ActionLink("Seel all clients", "Index", "Clients")</h3>


</body>

</html>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Eau Claire's Salon</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
    @RenderBody()
</body>

</html>

HairSalon/Views/Stylists/Create.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a new stylist</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.StylistName)
    @Html.TextBoxFor(model => model.StylistName)
    @Html.LabelFor(model => model.StylistDetails)
    @Html.TextBoxFor(model => model.StylistDetails)
    <input type="submit" value="Add new stylist" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Are you sure you want to delete this stylist?</h2>

@Html.DisplayNameFor(model => model.StylistName): @Html.DisplayFor(model => model.StylistName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to stylists", "Index")

HairSalon/Views/Stylists/Details.cshtml
@{
    Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Stylist;

<h2>Stylist Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.StylistName): @Html.DisplayFor(model => model.StylistName)</h3>
<h3>@Html.DisplayNameFor(model => model.StylistDetails): @Html.DisplayFor(model => model.StylistDetails)</h3>

<ul>
    @if (@Model.Clients.Count == 0)
    {
        <p>no clients found</p>
    }

    @foreach (Client client in @Model.Clients)
    {
        <li>Client Name: @client.ClientName</li>
    }
</ul>

<p>@Html.ActionLink("Back to stylists", "Index")</p>
<p>@Html.ActionLink("Edit Stylist Information", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this Stylist: @Html.DisplayFor(model => model.StylistName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StylistId)

    @Html.LabelFor(model => model.StylistName)
    @Html.EditorFor(model => model.StylistName)
    @Html.LabelFor(model => model.StylistDetails)
    @Html.EditorFor(model => model.StylistDetails)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to stylists", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
    Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h1>Your Stylists:</h1>

@if (@Model.Count == 0)
{
    <h3>No stylists have been added yet!</h3>
}

@foreach (Stylist stylist in Model)
{
    <li>@Html.ActionLink($"{stylist.StylistName}", "Details", new { id = stylist.StylistId })</li>
}

<p>@Html.ActionLink("Add new stylist", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>